# FROM node:latest
# RUN mkdir -p /
# WORKDIR /src
# # EXPOSE 3000
# COPY   ["./package.json","/src"]
# COPY ./. /src/.
# RUN npm install
# #RUN npm run build
# ENTRYPOINT npm start
# FROM nginx:alpine
# WORKDIR /usr/share/nginx/html
# RUN rm -rf ./*
# COPY --from=builder /app/build .
# ENTRYPOINT ["nginx", "-g", "daemon off;"]

FROM node:16 AS builder
WORKDIR /app
COPY . .
RUN yarn install && yarn build

FROM nginx:alpine
WORKDIR /usr/share/nginx/html
RUN rm -rf ./*
COPY --from=builder /app/build .
ENTRYPOINT ["nginx", "-g", "daemon off;"]

